export const supabaseUrl = 'https://cvcxphezvoclbkdardtg.supabase.co'
export const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2Y3hwaGV6dm9jbGJrZGFyZHRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTc0OTE5MTQsImV4cCI6MjAzMzA2NzkxNH0.vumkPMslKvTlNkkjb_R3XBjNnlAttL98Ert2MWqcNCE'
